describe('Main Page', () => {
    beforeEach(() => {
      cy.fixture('questions.json').then((questionData) => {
        cy.intercept('https://opentdb.com/api.php?amount=12&category=12&difficulty=medium&type=multiple', questionData)
      })
      cy.visit('http://localhost:3000/')
    })
  
    it('Should be able to visit http://localhost:3000 and see a title rendered', () => {
      cy
        .get('header')
        .contains('Are you the Maestro?')
    })

    it('Should be able to vist the main page and see "Welcome" with a message to start the game', () => {
        cy
          .get('.greeting-container')
          .get('h2')
          .contains('Welcome!')

          .get('p')
          .contains('Please try your hand at our music trivia game and see if you are a music maestro!')
    })

    it('Should have a button visible that indicates that a game can start', () => {
        cy
          .get('.greeting-container')
          .get('button')
          .contains('Start Game')
    })

    it('Should be able to click on the "Start Game" button and be taken to the first question', () => {
        cy 
          .get('.greeting-container')
          .get('button')
          .click()
          .url()
          .should('eq','http://localhost:3000/question/0')
          
    })  

    it('Should be able to view the initial score of 0 at the top of the question card', () => {
        cy 
          .get('.greeting-container')
          .get('button')
          .click()
          .get('.score-save-box')
          .get('p')
          .contains("Score: 0")
    })

    it('Should be able to see a question at the top of the question card', () => {
        cy
          .get('.greeting-container')
          .get('button')
          .click()
          .get('h3')
          .contains('What French artist/band is known for playing on the midi instrument "Launchpad"?')
    })

    it('Should be able to click on a checkbox', () => {
        cy
          .get('.greeting-container')
          .get('button')
          .click()
          .get(':nth-child(1) > input')
          .check()
          .should('be.checked')
    })

    it('Should be able to click on a checkbox and see the score change', () => {
        cy
          .get('.greeting-container')
          .get('button')
          .click()
          .get(':nth-child(1) > input')
          .check()
          .get('.score-save-box')
          .get('p')
          .contains("Score: -10")
    })

    it('Should see a message giving feedback about the answer provided', () => {
      cy
          .get('.greeting-container')
          .get('button')
          .click()
          .get(':nth-child(1) > input')
          .check()
          .get('.answer-feedback')
          .contains('Oooh, we\'re sorry! That\'s the wrong answer.')
    })

    it('Should be able to select an answer and then move on to the next question', () => {
      cy
        .get('.greeting-container')
        .get('button')
        .click()
        .get(':nth-child(1) > input')
        .check()
        .get('button')
        .click()
        .get('button')
        .click()
        .get('h3')
        .contains('In the song "The Ultimate Showdown of Ultimate Destiny" who is the only one to survive the battle?')
    })

    it('Should be able to save game after moving through all the questions', () => {
      cy
        .get('button')
        .click()
        .get(':nth-child(1) > input')
        .check()
        .get('button')
        .click()
        .get('button')
        .click()
        .get('button')
        .click()
        .get('button')
        .click()
        .get('button')
        .click()
        .get('button')
        .click()
        .get('button')
        .click()
        .get('button')
        .click()
        .get('button')
        .click()
        .get('button')
        .click()
        .get('button')
        .click()
        .get('button')
        .click()
        .get('button')
        .click()
        .get('button')
        .click()
        .get('button')
        .click()
        .get('button')
        .click()
        .get('button')
        .click()
        .get('button')
        .click()
        .get('button')
        .click()
        .get('button')
        .click()
        .get('button')
        .click()
        .get('button')
        .click()
        .get('button')
        .click()
        .get('.save-game-btn')
        .click()
        .get('h4')
        .contains('Your game on')
    })

    it('Should be able to see "Game Over" after moving through all the questions', () => {
      cy
        .get('button')
        .click()
        .get(':nth-child(1) > input')
        .check()
        .get('button')
        .click()
        .get('button')
        .click()
        .get('button')
        .click()
        .get('button')
        .click()
        .get('button')
        .click()
        .get('button')
        .click()
        .get('button')
        .click()
        .get('button')
        .click()
        .get('button')
        .click()
        .get('button')
        .click()
        .get('button')
        .click()
        .get('button')
        .click()
        .get('button')
        .click()
        .get('button')
        .click()
        .get('button')
        .click()
        .get('button')
        .click()
        .get('button')
        .click()
        .get('button')
        .click()
        .get('button')
        .click()
        .get('button')
        .click()
        .get('button')
        .click()
        .get('button')
        .click()
        .get('button')
        .click()
        .get('.gameover')
        .contains('Game Over')
    })
    
    it('Should be able to return home after moving through all the questions', () => {
      cy
        .get('button')
        .click()
        .get(':nth-child(1) > input')
        .check()
        .get('button')
        .click()
        .get('button')
        .click()
        .get('button')
        .click()
        .get('button')
        .click()
        .get('button')
        .click()
        .get('button')
        .click()
        .get('button')
        .click()
        .get('button')
        .click()
        .get('button')
        .click()
        .get('button')
        .click()
        .get('button')
        .click()
        .get('button')
        .click()
        .get('button')
        .click()
        .get('button')
        .click()
        .get('button')
        .click()
        .get('button')
        .click()
        .get('button')
        .click()
        .get('button')
        .click()
        .get('button')
        .click()
        .get('button')
        .click()
        .get('button')
        .click()
        .get('button')
        .click()
        .get('button')
        .click()
        .get('return-home-btn')
        .contains('Return Home')
    })
  })
  